import { BadgeCheck, Calculator, Dices, FlaskConical } from "lucide-react";

import { cn } from "@/lib/utils";

/**
 * Where a card's numbers come from.
 *
 *  - official:  MOIL SEBI / NSE corporate filings (depth, mine type, ore profile).
 *  - modelled:  deterministic formulas applied to the current inputs.
 *  - simulated: hand-authored placeholder / illustrative fixtures.
 *  - synthetic: seeded PRNG output (mulberry32), reproducible but not measured.
 *
 * `null` is reserved for guidance cards that carry no data at all.
 */
export type Provenance = "official" | "modelled" | "simulated" | "synthetic";

const META: Record<
  Provenance,
  { label: string; title: string; icon: typeof BadgeCheck; className: string }
> = {
  official: {
    label: "Official MOIL NSE",
    title: "Sourced from MOIL SEBI / NSE corporate filings.",
    icon: BadgeCheck,
    className: "border-teal/25 bg-teal-soft text-teal",
  },
  modelled: {
    label: "Modelled",
    title: "Calculated by the deterministic scenario model from the current inputs.",
    icon: Calculator,
    className: "border-sky-200 bg-sky-50 text-sky-800",
  },
  simulated: {
    label: "Simulated",
    title: "Illustrative placeholder data. Not measured or officially reported.",
    icon: FlaskConical,
    className: "border-amber-200 bg-amber-50 text-amber-900",
  },
  synthetic: {
    label: "Synthetic PRNG",
    title: "Generated by a seeded pseudo-random generator. Reproducible, not measured.",
    icon: Dices,
    className: "border-violet-200 bg-violet-50 text-violet-800",
  },
};

export function ProvenanceBadge({
  kind,
  className,
}: {
  kind: Provenance;
  className?: string | undefined;
}) {
  const meta = META[kind];
  const Icon = meta.icon;

  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 font-mono text-[8.5px] font-bold uppercase tracking-[0.08em]",
        meta.className,
        className,
      )}
      title={meta.title}
    >
      <Icon className="size-2.5" aria-hidden="true" />
      <span className="sr-only">Data provenance: </span>
      {meta.label}
    </span>
  );
}
